-- 100 городов, рандомное число до 82 потому что регионов в таблице regions 82.
-- К одному региону может относиться несколько городов
-- Так как id регионов сгенерированы рандомно, города и их реальные регионы могут не совпадать

INSERT INTO cities(name, region_id)
VALUES ('Москва', (SELECT (1+ RANDOM() * 82))),
('Санкт-Петербург', (SELECT (1+ RANDOM() * 82))),
('Новосибирск', (SELECT (1+ RANDOM() * 82))),
('Екатеринбург', (SELECT (1+ RANDOM() * 82))),
('Казань', (SELECT (1+ RANDOM() * 82))),
('Нижний Новгород', (SELECT (1+ RANDOM() * 82))),
('Челябинск', (SELECT (1+ RANDOM() * 82))),
('Красноярск', (SELECT (1+ RANDOM() * 82))),
('Самара', (SELECT (1+ RANDOM() * 82))),
('Уфа', (SELECT (1+ RANDOM() * 82))),
('Ростов-на-Дону', (SELECT (1+ RANDOM() * 82))),
('Омск', (SELECT (1+ RANDOM() * 82))),
('Краснодар', (SELECT (1+ RANDOM() * 82))),
('Воронеж', (SELECT (1+ RANDOM() * 82))),
('Пермь', (SELECT (1+ RANDOM() * 82))),
('Волгоград', (SELECT (1+ RANDOM() * 82))),
('Саратов', (SELECT (1+ RANDOM() * 82))),
('Тюмень', (SELECT (1+ RANDOM() * 82))),
('Тольятти', (SELECT (1+ RANDOM() * 82))),
('Барнаул', (SELECT (1+ RANDOM() * 82))),
('Ижевск', (SELECT (1+ RANDOM() * 82))),
('Махачкала', (SELECT (1+ RANDOM() * 82))),
('Хабаровск', (SELECT (1+ RANDOM() * 82))),
('Ульяновск', (SELECT (1+ RANDOM() * 82))),
('Иркутск', (SELECT (1+ RANDOM() * 82))),
('Владивосток', (SELECT (1+ RANDOM() * 82))),
('Ярославль', (SELECT (1+ RANDOM() * 82))),
('Кемерово', (SELECT (1+ RANDOM() * 82))),
('Томск', (SELECT (1+ RANDOM() * 82))),
('Набережные Челны', (SELECT (1+ RANDOM() * 82))),
('Севастополь', (SELECT (1+ RANDOM() * 82))),
('Ставрополь', (SELECT (1+ RANDOM() * 82))),
('Оренбург', (SELECT (1+ RANDOM() * 82))),
('Новокузнецк', (SELECT (1+ RANDOM() * 82))),
('Рязань', (SELECT (1+ RANDOM() * 82))),
('Балашиха', (SELECT (1+ RANDOM() * 82))),
('Пенза', (SELECT (1+ RANDOM() * 82))),
('Чебоксары', (SELECT (1+ RANDOM() * 82))),
('Липецк', (SELECT (1+ RANDOM() * 82))),
('Калининград', (SELECT (1+ RANDOM() * 82))),
('Астрахань', (SELECT (1+ RANDOM() * 82))),
('Тула', (SELECT (1+ RANDOM() * 82))),
('Киров', (SELECT (1+ RANDOM() * 82))),
('Сочи', (SELECT (1+ RANDOM() * 82))),
('Курск', (SELECT (1+ RANDOM() * 82))),
('Улан-Удэ', (SELECT (1+ RANDOM() * 82))),
('Тверь', (SELECT (1+ RANDOM() * 82))),
('Магнитогорск', (SELECT (1+ RANDOM() * 82))),
('Сургут', (SELECT (1+ RANDOM() * 82))),
('Брянск', (SELECT (1+ RANDOM() * 82))),
('Иваново', (SELECT (1+ RANDOM() * 82))),
('Якутск', (SELECT (1+ RANDOM() * 82))),
('Владимир', (SELECT (1+ RANDOM() * 82))),
('Симферополь', (SELECT (1+ RANDOM() * 82))),
('Белгород', (SELECT (1+ RANDOM() * 82))),
('Нижний Тагил', (SELECT (1+ RANDOM() * 82))),
('Калуга', (SELECT (1+ RANDOM() * 82))),
('Чита', (SELECT (1+ RANDOM() * 82))),
('Грозный', (SELECT (1+ RANDOM() * 82))),
('Волжский', (SELECT (1+ RANDOM() * 82))),
('Смоленск', (SELECT (1+ RANDOM() * 82))),
('Подольск', (SELECT (1+ RANDOM() * 82))),
('Саранск', (SELECT (1+ RANDOM() * 82))),
('Вологда', (SELECT (1+ RANDOM() * 82))),
('Курган', (SELECT (1+ RANDOM() * 82))),
('Череповец', (SELECT (1+ RANDOM() * 82))),
('Орел', (SELECT (1+ RANDOM() * 82))),
('Архангельск', (SELECT (1+ RANDOM() * 82))),
('Владикавказ', (SELECT (1+ RANDOM() * 82))),
('Нижневартовск', (SELECT (1+ RANDOM() * 82))),
('Йошкар-Ола', (SELECT (1+ RANDOM() * 82))),
('Стерлитамак', (SELECT (1+ RANDOM() * 82))),
('Мурманск', (SELECT (1+ RANDOM() * 82))),
('Кострома', (SELECT (1+ RANDOM() * 82))),
('Новороссийск', (SELECT (1+ RANDOM() * 82))),
('Тамбов', (SELECT (1+ RANDOM() * 82))),
('Химки', (SELECT (1+ RANDOM() * 82))),
('Мытищи', (SELECT (1+ RANDOM() * 82))),
('Нальчик', (SELECT (1+ RANDOM() * 82))),
('Таганрог', (SELECT (1+ RANDOM() * 82))),
('Нижнекамск', (SELECT (1+ RANDOM() * 82))),
('Благовещенск', (SELECT (1+ RANDOM() * 82))),
('Комсомольск-на-Амуре', (SELECT (1+ RANDOM() * 82))),
('Петрозаводск', (SELECT (1+ RANDOM() * 82))),
('Королев', (SELECT (1+ RANDOM() * 82))),
('Великий Новгород', (SELECT (1+ RANDOM() * 82))),
('Люберцы', (SELECT (1+ RANDOM() * 82))),
('Братск', (SELECT (1+ RANDOM() * 82))),
('Старый Оскол', (SELECT (1+ RANDOM() * 82))),
('Ангарск', (SELECT (1+ RANDOM() * 82))),
('Сыктывкар', (SELECT (1+ RANDOM() * 82))),
('Дзержинск', (SELECT (1+ RANDOM() * 82))),
('Псков', (SELECT (1+ RANDOM() * 82))),
('Орск', (SELECT (1+ RANDOM() * 82))),
('Красногорск', (SELECT (1+ RANDOM() * 82))),
('Армавир', (SELECT (1+ RANDOM() * 82))),
('Абакан', (SELECT (1+ RANDOM() * 82))),
('Балаково', (SELECT (1+ RANDOM() * 82))),
('Бийск', (SELECT (1+ RANDOM() * 82))),
('Южно-Сахалинск', (SELECT (1+ RANDOM() * 82)));